# Generated by Django 2.1.2 on 2018-10-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_roll', models.IntegerField()),
                ('st_name', models.TextField(blank=True, null=True)),
                ('st_class', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year')], default='FE', max_length=10)),
                ('st_age', models.IntegerField()),
                ('st_address', models.TextField(blank=True, null=True)),
                ('st_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
